#!/bin/bash
echo "installing cni plugins"
DEST=/opt/cni/bin
mkdir -p $DEST

for c in bridge loopback macvlan dhcp; do
    echo " -> $c"
    cp -f $c $DEST/
    chmod +x $DEST/$c
done

echo "cni plugin installation successful"
