#!/bin/bash
echo "Installing kernel"

dpkg -i ./linux-headers.deb >/dev/null
dpkg -i ./linux-image.deb >/dev/null

echo "installation complete"
echo ""
echo "NOTE: you must reboot to activate the new kernel..."
