#!/bin/bash
set -e
echo "installing buildkit"
for c in buildctl buildkitd; do
    echo " -> $c"
    cp -f $c /usr/local/bin/
    chmod +x /usr/local/bin/$c
done

CONFIG=/etc/buildkitd.conf

echo " -> configuring buildkit"
if [ ! -z "${TERRA_BUILDKIT_ADDR}" ]; then
    cat << EOF > ${CONFIG}
[grpc]
address = ["${TERRA_BUILDKIT_ADDR}"]
EOF
else
    # defaults
    touch ${CONFIG}
fi

echo " -> configuring systemd"
cp buildkit.service /etc/systemd/system/buildkit.service
systemctl daemon-reload
systemctl enable buildkit
systemctl restart buildkit

echo " -> $(buildkitd -v)"
echo "buildkit installation successful"
